title: Super Page!
author: Peter!
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Super duper page
  the best ever

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
